name: Build and Push Docker Image used in integration tests

on:
  push:
    paths:
      - 'ci/docker/integration.dockerfile'
  pull_request:
    paths:
      - 'ci/docker/integration.dockerfile'
  schedule:
    # Run on the 1st day of every other month at 00:00 UTC (approximately every 60 days)
    - cron: '0 0 1 */2 *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and export Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ci/docker/integration.dockerfile
        tags: sparrow-integration-tests:latest
        outputs: type=docker,dest=/tmp/sparrow-integration-image.tar
        push: false
        
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: sparrow-integration-image
        path: /tmp/sparrow-integration-image.tar
        compression-level: 0