name: Build and Push Docker Image used in integration tests

on:
  push:
    paths:
      - 'ci/docker/integration.dockerfile'
  pull_request:
    paths:
      - 'ci/docker/integration.dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: docker build -t ghcr.io/man-group/sparrow-integration-tests -f ci/docker/integration.dockerfile .

    - name: Push Docker image
      run: docker push ghcr.io/man-group/sparrow-integration-tests:latest
