name: Build and Push Docker Image used in integration tests

permissions: write-all

on:
  push:
    paths:
      - 'ci/docker/integration.dockerfile'
  pull_request:
    paths:
      - 'ci/docker/integration.dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ci/docker/integration.dockerfile
        push: true
        tags: sparrow/integration_tests:latest
        cache-from: type=registry,ref=sparrow/integration_tests:latest
        cache-to: type=inline,mode=min
