name: Integration

on:
  permissions: write-all
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download docker integration test image artifact
        uses: actions/download-artifact@v4
        with:
          name: sparrow-integration-image
          path: ${{ runner.temp }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/sparrow-integration-image.tar
          docker image ls -a