name: 'Test Report'
on:
  workflow_run:
    workflows: [Linux]
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test_sparrow_lib_report_Linux_(.*)
        name: Process test report
        path: '**/*.xml'
        reporter: java-junit
